apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-service
      containers:
      - name: jenkins
        image: docker.io/amr966/jenkins:v1
        ports:
        - containerPort: 8080

        volumeMounts:
          - name: var-run
            mountPath: /var/run
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
    
        